name: CI - Lint & Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm' # Speeds up future runs by caching node_modules

            - name: Install dependencies
              run: npm ci # Faster, "clean" install for CI environments

            - name: Check Formatting
              run: npm run format:check

            - name: Check Linting
              run: npm run lint

            - name: Run Tests
              run: npm run test
